openapi: 3.0.0

info:
  version: 0.0.1
  title: Prompt Registry API
  description: Prompt Storage service for Design time & Runtime prompt templates.

paths:
  /healthz:
    get:
      operationId: registry.controller.prompt_controller.healthz
      responses:
        "200":
          description: "Service is up and running."
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
        "503":
          description: "Service is unavailable."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Service Unavailable"
  /internal/promptTemplates/provisioning:
    parameters:
    - in: header
      name: AI-Main-Tenant
      required: true
      schema:
        type: string
      description: The main tenant name
    post:
      operationId: registry.controller.prompt_controller.onboard_tenant
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisioningResponse"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
    delete:
      operationId: registry.controller.prompt_controller.offboard_tenant
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisioningResponse"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/promptTemplates:
    post:
      operationId: registry.controller.prompt_controller.create_update_prompt_template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptTemplatePostRequest"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplatePostResponse"
        403:
          $ref: "#/components/responses/ForbiddenError"
        400:
          $ref: "#/components/responses/BadRequest"
        default:
          $ref: "#/components/responses/CommonError"
    get:
      operationId: registry.controller.prompt_controller.list_prompt_templates
      parameters:
        - name: scenario
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            type: string
        - name: version
          in: query
          schema:
            type: string
        - name: retrieve
          in: query
          schema:
            type: string
            default: both
        - name: includeSpec
          in: query
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateListResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/scenarios/{scenario}/promptTemplates/{name}/versions/{version}/history:
    get:
      operationId: registry.controller.prompt_controller.list_prompt_template_history
      parameters:
        - name: scenario
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateListResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/promptTemplates/{promptTemplateId}:
    get:
      operationId: registry.controller.prompt_controller.get_prompt_template_by_uuid
      parameters:
        - name: promptTemplateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateGetResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
    delete:
      operationId: registry.controller.prompt_controller.delete_prompt_template
      parameters:
        - name: promptTemplateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateDeleteResponse"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/promptTemplates/import:
    post:
      operationId: registry.controller.prompt_controller.import_prompt_template
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplatePostResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/promptTemplates/{promptTemplateId}/export:
    get:
      operationId: registry.controller.prompt_controller.export_prompt_template
      parameters:
        - name: promptTemplateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful response
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          $ref: "#/components/responses/BadRequest"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/promptTemplates/{promptTemplateId}/substitution:
    post:
      operationId: registry.controller.prompt_controller.parse_prompt_template_by_id
      parameters:
        - name: promptTemplateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: metadata
          in: query
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptTemplateSubstitutionRequest"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateSubstitutionResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"
  /lm/scenarios/{scenario}/promptTemplates/{name}/versions/{version}/substitution:
    post:
      operationId: registry.controller.prompt_controller.parse_prompt_template_by_name_version
      parameters:
        - name: scenario
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: metadata
          in: query
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptTemplateSubstitutionRequest"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplateSubstitutionResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        403:
          $ref: "#/components/responses/ForbiddenError"
        default:
          $ref: "#/components/responses/CommonError"

components:
  schemas:
    ProvisioningResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Template:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
        content:
          type: string
    PromptTemplateSpec:
      type: object
      required:
        - template
      properties:
        template:
          type: array
          items:
            $ref: "#/components/schemas/Template"
        defaults:
          type: object
        additionalFields:
          type: object
    PromptTemplatePostRequest:
      type: object
      required:
        - name
        - version
        - scenario
        - spec
      properties:
        name:
          type: string
        version:
          type: string
        scenario:
          type: string
        spec:
          $ref: "#/components/schemas/PromptTemplateSpec"
    PromptTemplatePostResponse:
      type: object
      required:
        - message
        - id
        - scenario
        - name
        - version
      properties:
        message:
          type: string
        id:
          type: string
          format: uuid
        scenario:
          type: string
        name:
          type: string
        version:
          type: string
    PromptTemplateGetResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        version:
          type: string
        scenario:
          type: string
        creationTimestamp:
          type: string
          format: timestamp
        managedBy:
          type: string
        isVersionHead:
          type: boolean
        spec:
          $ref: "#/components/schemas/PromptTemplateSpec"
    PromptTemplateListResponse:
      type: object
      required:
        - count
        - resources
      properties:
        count:
          type: integer
        resources:
          type: array
          items:
            $ref: "#/components/schemas/PromptTemplateGetResponse"
    PromptTemplateDeleteResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    RuntimePromptTemplateFile:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            version:
              type: string
            scenario:
              type: string
        spec:
          $ref: "#/components/schemas/PromptTemplateSpec"
    PromptTemplateSubstitutionRequest:
      type: object
      properties:
        inputParams:
          type: object
    PromptTemplateSubstitutionResponse:
      type: object
      properties:
        parsedPrompt:
          type: array
          items:
            $ref: "#/components/schemas/Template"
        resource:
          $ref: "#/components/schemas/PromptTemplateGetResponse"
    ErrorResponse:
      type: object
      required:
        - request_id
        - message
      properties:
        request_id:
          type: string
        message:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    CommonError:
      description: Common Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ForbiddenError:
      description: Forbidden Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"